template_project/basic_app/urls.py
from django.urls import path
from . import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('relative_url_templates/', views.relative_url_templates, name='relative_url_templates'),
    path('other/', views.other, name='other'),
    path('registration/', views.registration, name='registration'),
    path('user_login/',views.user_login,name='user_login'),

]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

template_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

template_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

template_project/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in.')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def other(request):
    return render(request, 'basic_app/other.html')

def relative_url_templates(request):
    return render(request, 'basic_app/relative_url_templates.html')

def registration(request):
    """
    View for requesting registration information from a new user
    and saving the information provided to the database.
    """
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
            return render(request,'basic_app/thankyou.html')

        else:
            print(user_form.errors,profile_form.errors)
            return render(request,'basic_app/registration.html')

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

        return render(request,'basic_app/registration.html',context={'user_form':user_form,
                                                                    'profile_form':profile_form,
                                                                    'registered':registered})

def user_login(request):
    if request.method =='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print('Someone tried to log in and failed')
            print('Username: {} and password {}'.format(username,password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request,'basic_app/login.html',{})

template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class='navbar navbar-default navbar-static-top'>
        <div class='container'>
            <ul class='nav navbar-nav'>
                <li ><a class='navbar-brand' href="{% url 'basic_app:index' %}">BRAND</a></li>
                <li><a class='navbar-link' href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class='navbar-link' href="{% url 'basic_app:registration' %}">Register</a></li>
                <li><a class='navbar-link' href="{% url 'basic_app:other' %}">Other</a></li>
                <li><a class='navbar-link' href="{% url 'basic_app:relative_url_templates' %}">Relative</a></li>
                <li><a class='navbar-link' href="{% url 'special' %}">Special</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}" class ="navbar-link">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'basic_app:user_login' %}" class ="navbar-link">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}
        <!-- Anything outside this will be inherited if you extend. -->
        {% endblock %}

    </div>
</body>
</html>

template_project/templates/basic_app/index.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
{% load my_extras  %}


{% block body_block %}
<div class='jumbotron'>
    <h1>Django Level Five</h1>
</div>
{% endblock %}

template_project/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}

{% block body_block %}

<div class='jumbotron'>
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method='post'>
        {% csrf_token %}
        <label for="username" >Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

template_project/templates/basic_app/other.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %}

{% block body_block %}

<h1>Welcome to Other</h1>
<a href="{% url 'basic_app:relative_url_templates' %}">To Relative URL Templates webpage</a>
<br>
<a href="{% url 'admin:index' %}">Admin</a>

{% endblock %}

template_project/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class='jumbotron'>
    {% if registered %}
        <h1>Thank you for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Please fill out the form:</h3>

        <form  enctype="multipart/form-data" action="" method='post'>
            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input class='btn btn-primary' type="submit" value="Register">

        </form>
    {% endif %}
</div>

{% endblock %}

template_project/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}

    <h1>Welcome to Relative URL Templates</h1>
    <a href="{% url 'basic_app:other' %}">To Other webpage</a>
    <br>
    <a href="{% url 'index' %}">Index</a>
{% endblock %}

template_project/templates/basic_app/thankyou.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
<div class='jumbotron'>
    <h1>Thank you for registering!</h1>
</div>
{% endblock %}